version: "3.8"

services:
  backend:
    image: backend:latest
    build:
      context: .
    restart: unless-stopped
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
    healthcheck:
      test:
        - "CMD"
        - "sh"
        - "-c"
        - "curl --fail http://localhost:$(APP_PORT:-8000}/healthcheck || exit 1"
      interval: 60s
      timeout: 30s
      retries: 10
